/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'service' : string,
  'status' : string,
  'date' : string,
  'name' : string,
  'createdAt' : bigint,
  'time' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface _SERVICE {
  /**
   * / Book a new appointment. Returns the new appointment ID, or 0 on validation failure.
   */
  'bookAppointment' : ActorMethod<
    [string, string, string, string, string, string, string],
    bigint
  >,
  /**
   * / Cancel an appointment by ID. Returns true on success.
   */
  'cancelAppointment' : ActorMethod<[bigint], boolean>,
  /**
   * / Return a single appointment by ID, or null if not found.
   */
  'getAppointmentById' : ActorMethod<[bigint], [] | [Appointment]>,
  /**
   * / Return all appointments (admin use).
   */
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  /**
   * / Update the status of an appointment. Returns true on success.
   */
  'updateAppointmentStatus' : ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];