/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'status' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'time' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'bookAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'cancelAppointment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAppointmentById' : IDL.Func([IDL.Nat], [IDL.Opt(Appointment)], ['query']),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'updateAppointmentStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'status' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'time' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'bookAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'cancelAppointment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAppointmentById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Appointment)],
        ['query'],
      ),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'updateAppointmentStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };